USE youngry2;
##Creating the tables required
create table country (CountryCode Int(4) not null, CountryName varchar(45), primary key (CountryCode));
create table sponsor (SponsorID int(5) not null, name varchar(45), primary key (SponsorID));
create table convention (ConventionID varchar(10) not null, Title varchar(45), StartDate date, EndDate date, registrationFee int(4), LocationCity varchar(45), LocationStreet varchar(45), LocationNo int(5), LocationPostCode varchar(10), CountryCode int(4) not null, primary key (ConventionID, CountryCode), foreign key (CountryCode) references country(CountryCode));
create table convention_sponsor(ConventionID Char(10) not null, SponsorID int(5) not null, budget float, Primary key (ConventionID, SponsorID), foreign key (ConventionID) references convention(ConventionID), foreign key (SponsorID) references sponsor(SponsorID));
create table Discount (DiscountCode char(3) not null, ConventionID char(10) not null, percent int(3), primary key(DiscountCode, ConventionID), foreign key (ConventionID)references convention(ConventionID));
create table participant(ParticipantID int not null, Name varchar(45), DOB Date, Presenter Tinyint, primary key(ParticipantID));
create table session(SessionID int(3) not null, Subject varchar(45), Day date, StartTime text(5), FinishTime text(5), ConventionID CHAR(10), primary key(SessionID), foreign key(ConventionID) references convention(ConventionID));
create table session_participant(SessionID int(3), ParticipantID int, primary key(SessionID, ParticipantID), foreign key (SessionID) references session(SessionID), foreign key(ParticipantID) references participant(ParticipantID));
create table participant_fee(ParticipantID int, DiscountCode char(3), ConventionID char(10), primary key(ParticipantID, DiscountCode, ConventionID), foreign key (ParticipantID) references participant(ParticipantID), foreign key (DiscountCode) references Discount(DiscountCode), foreign key (ConventionID) references convention(ConventionID));
create table participant_convention(ParticipantID int, ConventionID char(10), primary key(ParticipantID, ConventionID),foreign key (ParticipantID) references participant(ParticipantID), foreign key (ConventionID) references convention(ConventionID));

##Select Statements to generate reports
Select Name from participant, (Select ParticipantID from session_participant, (Select SessionID from session, (Select ConventionID from convention where Title like "ITiCSE") as ConID where session.ConventionID like ConID.ConventionID and session.Subject like "debugging") as SesID where SesID.SessionID = session_participant.SessionID) as ParID where participant.ParticipantID = ParID.ParticipantID order by Name asc;
Select Name from (Select Name, count(ParID.SessionID) as count from participant, (Select ParticipantID, SesID.SessionID from session_participant, (Select SessionID from session, (Select ConventionID from convention where Title like "ITiCSE") as ConID where session.ConventionID like ConID.ConventionID) as SesID where SesID.SessionID = session_participant.SessionID) as ParID where participant.ParticipantID = ParID.ParticipantID group by Name) as Cnt where count >= 1 order by Name asc;
Select name from sponsor, (Select SponsorID from convention_sponsor where convention_sponsor.ConventionID = "100") as ConSpon where ConSpon.SponsorID = sponsor.SponsorID order by name;
Select Name, max_discount from participant, (Select participantID, max(percent) as max_discount from participant_fee, (Select DiscountCode, percent from Discount) as Disc where Disc.DiscountCode = participant_fee.DiscountCode group by ParticipantID) as PID where participant.ParticipantID = PID.participantID order by Name;
Select sponsor.name, Title, percent from sponsor inner join (Select SponsorID, convention_sponsor.ConventionID, percent, Title from convention_sponsor inner join (Select Title, convention.ConventionID, percent from convention inner join (Select ConventionID, max(percent) as percent from Discount where percent > 40 group by ConventionID) as Tab1) as Tab2) as Tab3 order by percent desc;
Select CountryName, Title, subject from country, (Select Tab1.ConventionID, Title, subject, CountryCode from convention, (Select ConventionID, subject from session where subject like "debugging" or subject like "programming") as Tab1 where Tab1.ConventionID = convention.ConventionID order by Title desc) as Tab2 where country.CountryCode = Tab2.CountryCode order by CountryName Asc;
Select ConventionID, sum(count) from session, (Select SessionID, count from (Select SessionID, Count(ParticipantID) as count from session_participant group by SessionID) as Tab1 where Tab1.count > 30) as Tab2 where session.SessionID = Tab2.SessionID group by ConventionID;
Select Sum(Total) as Total_Made from (Select ((1 - (percent/100))* 400) as Total, ParticipantID from (Select percent, ParticipantID from Discount, (Select * from participant_fee where ConventionID = "100") as Tab1 where Discount.DiscountCode = Tab1.DiscountCode) as Tab2) as Tab3;
